### ISSUE TITLE
Happy leap day

### ISSUE THREAD

**Issue by rtomayko** [tmm1/graphite#5]
Only triggered when an absolute date in 2011 is used. Like `from=20111201`. I know this worked a few days ago.

![](https://img.skitch.com/20120229-b1ud9a127hx6xbgb5b74jp37c4.png)

Traceback:

```
Traceback (most recent call last):
  File "/usr/share/graphite/lib/python2.5/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/graphite/webapp/graphite/render/views.py", line 46, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File "/usr/share/graphite/webapp/graphite/render/views.py", line 240, in parseOptions
    fromTime = parseATTime( queryParams['from'] )
  File "/usr/share/graphite/webapp/graphite/render/attime.py", line 35, in parseATTime
    return parseTimeReference(ref) + parseTimeOffset(offset)
  File "/usr/share/graphite/webapp/graphite/render/attime.py", line 84, in parseTimeReference
    refDate = refDate.replace(year= int(ref[:4]))
ValueError: day is out of range for month
```

**Comment by rtomayko** [comment]
Looks like it's here:

https://github.com/tmm1/graphite/blob/master/webapp/graphite/render/attime.py#L83-84

The year is being adjusted from the current time and there's no Feb 29 in 2011.

**Comment by rtomayko** [comment]
Closing as stale.
